/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun testParse() {
        val p = ParsedInput("cat")
        assertEquals("cat", p.command)
        assert(p.flags.isEmpty())
        assert(p.arguments.isEmpty())
    }
}
